useful resources added
NIT-Hamirpur-NITH/tipsNtricks pull request #25
Opened 2018-10-02 06:08 UTC by Dhanya-Abhirami

Added links for competitive coding, presentation framework and Online chat. Minor spelling fix done.

2018-10-02 13:51 UTC, Akarshit requested changes

2018-10-02 13:51 UTC, Akarshit commented on README.md
> +45. [**Hackerrank**](https://www.hackerrank.com/), [**Codechef**](https://www.codechef.com/) - Competitive Coding
These are already very well know, so I don't think there is benefit in adding these.

2018-10-02 13:51 UTC, Akarshit commented on README.md
> +46. [**reveal.js**](https://revealjs.com/#/) - Make slides wich open on browser
This won't be probably used by 99% of the viewers. So I don't see much potential adding this.

2018-10-03 12:40 UTC, Dhanya-Abhirami commented
I have updated it. Please check it.

2018-10-03 13:18 UTC, merged

2018-10-03 13:18 UTC, Akarshit commented
Thanks @Dhanya-Abhirami :)